services:
  - type: web
    name: hilltops-home-interior
    env: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:QUkLNYgjEiwhazPZc0vRa9c/PUGwu0RF7ZlGkqpH7v4=
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /app/database/database.sqlite
      - key: LOG_CHANNEL
        value: stderr
